[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --only=production"]

[phases.build]
cmds = ["echo 'No build step required for Node.js server'"]

[start]
cmd = "npm start" 